apiVersion: v2
name: sentry
description: A Helm chart for Kubernetes
type: application
version: 26.0.0
appVersion: 24.9.0
dependencies:
  - name: memcached
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 7.5.2
    condition: sourcemaps.enabled
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 17.11.3
    condition: redis.enabled
  - name: kafka
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 29.3.14
    condition: kafka.enabled
  - name: clickhouse
    repository: https://sentry-kubernetes.github.io/charts
    version: 3.13.0
    condition: clickhouse.enabled
  - name: zookeeper
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.4.11
    condition: zookeeper.enabled
  - name: rabbitmq
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.16.2
    alias: rabbitmq
    condition: rabbitmq.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.5.1
    condition: postgresql.enabled
  - name: nginx
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.2.2
    condition: nginx.enabled
maintainers:
  - name: sentry-kubernetes
