apiVersion: v1
appVersion: 3.6.0
description: A centralized service for maintaining configuration information, naming,
  providing distributed synchronization, and providing group services for distributed
  applications.
engine: gotpl
home: https://zookeeper.apache.org/
icon: https://bitnami.com/assets/stacks/zookeeper/img/zookeeper-stack-110x117.png
keywords:
- zookeeper
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: zookeeper
sources:
- https://github.com/bitnami/bitnami-docker-zookeeper
version: 5.7.2
