apiVersion: v1
entries:
  sentry:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.584423799Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.2
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.4
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - alias: rabbitmq
      condition: rabbitmq.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 510ed1ef45377e92db867846ebd8f029f7da4f29e1cecd12891df4096cfdf563
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.569697202Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 9.3.2
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 9.0.4
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - alias: rabbitmq
      condition: rabbitmq.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 70dc6a921a786fcc9d9c97cc198a75f7b1ae46d5c723509a28551fffa935ed04
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.596010097Z"
    description: A Helm chart for Kubernetes
    digest: ccf7aabac486a68779d6564d90a875b45fefa4e4a9e8f86903355cf886b6a3aa
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.595064197Z"
    description: A Helm chart for Kubernetes
    digest: 07b380bbb341bb276b962de0b3721c9142a97e9fd084a394fc4d9f5db75bceea
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.9.3.tgz
    version: 0.9.3
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.593873497Z"
    description: A Helm chart for Kubernetes
    digest: a5a52cb5362e604215b1811e053a1b790d8f2e6c0c553a55d52f0750a6f63936
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.592972597Z"
    description: A Helm chart for Kubernetes
    digest: 81e65b09754dea768122d4d619801bab77714f9c77520afbc1658c7bf68b563d
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.592031198Z"
    description: A Helm chart for Kubernetes
    digest: 225f13adbe6a002014b135afc02b65771fbb5bbdf6f09e3179a408beb316846c
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.590944598Z"
    description: A Helm chart for Kubernetes
    digest: aef5a5cd789251ab629d25d18ac94a7801e80fb99dde54dc98111e7547326ce8
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.589456898Z"
    description: A Helm chart for Kubernetes
    digest: 2ced97e545a92598f9b3bc487aa53b7b4cd6df8ba2b97ffbce5807a6e0a641d0
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.588113098Z"
    description: A Helm chart for Kubernetes
    digest: bf3b118679f72f65fa20120dfd4c1718b56694250e80dac285189a0073a2fbcc
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.587078499Z"
    description: A Helm chart for Kubernetes
    digest: b24391c885cb84817b024df7feb81feb6d97443a1e7cf26d6a7a04cdd3e1af0c
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.586202499Z"
    description: A Helm chart for Kubernetes
    digest: 476900c519773349f70e8d0171f870ba5ad7983c62fcc72ae3b7799948500f33
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.585315699Z"
    description: A Helm chart for Kubernetes
    digest: 0da209fcf559a3aa66ef7715cf6327da2337e3739fff89e06a25d2e6a1488765
    name: sentry
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-0.2.1.tgz
    version: 0.2.1
  sentry-db:
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.744526164Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: eb8fa75235442f43d3c2000473eef60e10ed58ce5eb1de506f8d5054c8379be4
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.9.4.tgz
    version: 0.9.4
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.731669267Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 4b7986994d2e79f3664facd592f705d5b0658ecda3584687c578bfb0db44b43b
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.9.3.tgz
    version: 0.9.3
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.71902937Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 85e5b6875d3e59f675d8bfc957a209d7755302fa235923086615a6b381f7b8c0
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.707056673Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: c225992e35fb2427eaf4ed6ef404e8ae4de4e89d8391f5abe321f29fd80ee154
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.694616875Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: c14162069acb7135e908e263fa20e05166e95cc5f4ad633fe6a0b8c7c8534c13
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.680299778Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: b125bb297c23d319dabe141536a9bd014538edf0b26d8847249aa28fe3627fa6
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.8.0.tgz
    version: 0.8.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.665453982Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: c61a9ea0ce22cc86d105d4d88e1e8f11ef65764847dce5b405fbd91419bf611a
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.650449285Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 24f7a94f3d6f194b5d1cf678467b4cec4551c398e83d615d2312e90466202db9
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.6.1.tgz
    version: 0.6.1
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.634903088Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 3b9097700de785f1bad79a99c9f469a920f984efe699a457f8ada5bb608b8417
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.619951892Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: 2bb4095a0774ccc5b418a1ca031889e1796ecf537bb1ff8e798b5b26a48f3b85
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 10.0.0
    created: "2020-04-10T05:45:10.607795194Z"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 10.3.3
    - condition: kafka.enabled
      name: kafka
      repository: https://charts.bitnami.com/bitnami
      version: 7.1.1
    - condition: clickhouse.enabled
      name: clickhouse
      repository: https://liwenhe1993.github.io/charts/
      version: 1.0.1
    - condition: rabbitmq-ha.enabled
      name: rabbitmq-ha
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 1.38.2
    - condition: postgresql.enabled
      name: postgresql
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 8.2.1
    description: A Helm chart for Kubernetes
    digest: ca96424a03a019c13e38bfb1a870081f8ade5b1503b493925732c0b8000d11b0
    name: sentry-db
    type: application
    urls:
    - https://sentry-kubernetes.github.io/charts/sentry-db-0.2.1.tgz
    version: 0.2.1
generated: "2020-04-10T05:45:10.552881606Z"
