{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-nginx
data:
  server-block.conf: |
    upstream relay {
      server {{ template "sentry.fullname" . }}-relay:{{ template "relay.port" }};
    }

    upstream sentry {
      server {{ template "sentry.fullname" . }}-web:{{ template "sentry.port" }};
    }

    server {
      listen {{ template "nginx.port" }};

      proxy_redirect off;
      proxy_buffer_size          128k;
      proxy_buffers              4 256k;
      proxy_busy_buffers_size    256k;
      proxy_set_header Host $host;

      location /api/store/ {
        proxy_pass http://relay;
      }

      location ~ ^/api/[1-9]\d*/ {
        proxy_pass http://relay;
      }  

      {{ if or .Values.nginx.metrics.enabled .Values.nginx.metrics.serviceMonitor.enabled -}}
      location = /status/ {
        stub_status on;
        access_log off;
      }

      {{ end -}}

      location / {
        proxy_pass http://sentry;
      }

      location /_static/ {
        proxy_pass http://sentry;
        proxy_hide_header Content-Disposition;
      }
    }
{{- end }}
