{{- if .Values.snuba.issueOccurrenceConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-issue-occurrence-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "16"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: issue-occurrence-consumer
  replicas: {{ .Values.snuba.issueOccurrenceConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.issueOccurrenceConsumer.annotations }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: issue-occurrence-consumer
        {{- if .Values.snuba.issueOccurrenceConsumer.podLabels }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.issueOccurrenceConsumer.affinity }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.issueOccurrenceConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.issueOccurrenceConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.issueOccurrenceConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.issueOccurrenceConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.issueOccurrenceConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.issueOccurrenceConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "consumer"
          - "--storage"
          - "search_issues"
          - "--consumer-group"
          - "generic_events_group"
          - "--auto-offset-reset"
          - "{{ .Values.snuba.issueOccurrenceConsumer.autoOffsetReset }}"
          - "--max-batch-time-ms"
          - "750"
          {{- if .Values.snuba.issueOccurrenceConsumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.snuba.issueOccurrenceConsumer.maxBatchSize }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.processes }}
          - "--processes"
          - "{{ .Values.snuba.issueOccurrenceConsumer.processes }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.inputBlockSize }}
          - "--input-block-size"
          - "{{ .Values.snuba.issueOccurrenceConsumer.inputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.outputBlockSize }}
          - "--output-block-size"
          - "{{ .Values.snuba.issueOccurrenceConsumer.outputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.issueOccurrenceConsumer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.issueOccurrenceConsumer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.issueOccurrenceConsumer.queuedMinMessages }}"
          {{- end }}
          {{- if .Values.snuba.issueOccurrenceConsumer.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.issueOccurrenceConsumer.env }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.issueOccurrenceConsumer.volumeMounts }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.issueOccurrenceConsumer.resources | indent 12 }}
{{- if .Values.snuba.issueOccurrenceConsumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.issueOccurrenceConsumer.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.issueOccurrenceConsumer.volumes }}
{{ toYaml .Values.snuba.issueOccurrenceConsumer.volumes | indent 8 }}
{{- end }}
{{- end }}
