{{- if .Values.sentry.cron.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-cron
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: cron
  replicas: {{ .Values.sentry.cron.replicas }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.config" . | sha256sum }}
        {{- if .Values.sentry.cron.annotations }}
{{ toYaml .Values.sentry.cron.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: cron
        {{- if .Values.sentry.cron.podLabels }}
{{ toYaml .Values.sentry.cron.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.cron.affinity }}
{{ toYaml .Values.sentry.cron.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.cron.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.cron.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.cron.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.cron.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.cron.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.cron.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-cron
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "cron"
          {{- if .Values.sentry.cron.logLevel }}
          - "-l{{ .Values.sentry.cron.logLevel}}"
          {{- end }}
        env:
        - name: C_FORCE_ROOT
          value: "true"
{{ include "sentry.env" . | indent 8 }}
{{- if .Values.sentry.cron.env }}
{{ toYaml .Values.sentry.cron.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
        {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.cron.volumeMounts }}
{{ toYaml .Values.sentry.cron.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.cron.resources | indent 12 }}
{{- if .Values.sentry.cron.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.cron.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.cron.sidecars }}
{{ toYaml .Values.sentry.cron.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-cron
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ .Values.filestore.gcs.secretName }}
      {{ end }}
{{- if .Values.sentry.cron.volumes }}
{{ toYaml .Values.sentry.cron.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.cron.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.cron.priorityClassName }}"
      {{- end }}
{{- end }}
