{{- if .Values.snuba.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-consumer
  replicas: {{ .Values.snuba.consumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.consumer.annotations }}
{{ toYaml .Values.snuba.consumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-consumer
        {{- if .Values.snuba.consumer.podLabels }}
{{ toYaml .Values.snuba.consumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.consumer.affinity }}
{{ toYaml .Values.snuba.consumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.consumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.consumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.consumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.consumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.consumer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.consumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "consumer"
          - "--storage"
          - "errors"
          - "--auto-offset-reset"
          - "{{ .Values.snuba.consumer.autoOffsetReset }}"
          - "--max-batch-time-ms"
          - "750"
          {{- if .Values.snuba.consumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.snuba.consumer.maxBatchSize }}"
          {{- end }}
          {{- if .Values.snuba.consumer.processes }}
          - "--processes"
          - "{{ .Values.snuba.consumer.processes }}"
          {{- end }}
          {{- if .Values.snuba.consumer.inputBlockSize }}
          - "--input-block-size"
          - "{{ .Values.snuba.consumer.inputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.consumer.outputBlockSize }}
          - "--output-block-size"
          - "{{ .Values.snuba.consumer.outputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.consumer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.consumer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.consumer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.consumer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.consumer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.consumer.queuedMinMessages }}"
          {{- end }}
          {{- if .Values.snuba.consumer.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.consumer.env }}
{{ toYaml .Values.snuba.consumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.consumer.volumeMounts }}
{{ toYaml .Values.snuba.consumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.consumer.resources | indent 12 }}
{{- if .Values.snuba.consumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.consumer.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.consumer.volumes }}
{{ toYaml .Values.snuba.consumer.volumes | indent 8 }}
{{- end }}
{{- end }}
