apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-sessions-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  {{- if .Values.asHook }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "16"
  {{- end }}
spec:
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: sessions-consumer
  replicas: {{ .Values.snuba.sessionsConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.sessionsConsumer.annotations }}
{{ toYaml .Values.snuba.sessionsConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: sessions-consumer
        {{- if .Values.snuba.sessionsConsumer.podLabels }}
{{ toYaml .Values.snuba.sessionsConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.sessionsConsumer.affinity }}
{{ toYaml .Values.snuba.sessionsConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.sessionsConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.sessionsConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.sessionsConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.sessionsConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command: ["snuba", "consumer", "--storage", "sessions_raw", "--auto-offset-reset=latest", "--max-batch-time-ms", "750"]
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
        - name: SNUBA_SETTINGS
          value: /etc/snuba/settings.py
{{- if .Values.snuba.sessionsConsumer.env }}
{{ toYaml .Values.snuba.sessionsConsumer.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.snuba.sessionsConsumer.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
