{{- if .Values.snuba.spansConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-spans-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "12"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-spans-consumer
  replicas: {{ .Values.snuba.spansConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.spansConsumer.annotations }}
{{ toYaml .Values.snuba.spansConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-spans-consumer
        {{- if .Values.snuba.spansConsumer.podLabels }}
{{ toYaml .Values.snuba.spansConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.spansConsumer.affinity }}
{{ toYaml .Values.snuba.spansConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.spansConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.spansConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.spansConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.spansConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.spansConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.spansConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - {{ if .Values.snuba.rustConsumer -}}"rust-consumer"{{- else -}}"consumer"{{- end }}
          - "--storage"
          - "spans"
          - "--consumer-group"
          - "snuba-spans-group"
          - "--auto-offset-reset"
          - "{{ .Values.snuba.spansConsumer.autoOffsetReset }}"
          - "--max-batch-time-ms"
          - "750"
          {{- if .Values.snuba.spansConsumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.snuba.spansConsumer.maxBatchSize }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.processes }}
          - "--processes"
          - "{{ .Values.snuba.spansConsumer.processes }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.inputBlockSize }}
          - "--input-block-size"
          - "{{ .Values.snuba.spansConsumer.inputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.outputBlockSize }}
          - "--output-block-size"
          - "{{ .Values.snuba.spansConsumer.outputBlockSize }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.spansConsumer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.spansConsumer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.spansConsumer.queuedMinMessages }}"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          {{- if .Values.snuba.spansConsumer.livenessProbe.enabled }}
          - "--health-check-file"
          - "/tmp/health.txt"
          {{- end }}
        {{- if .Values.snuba.spansConsumer.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.snuba.spansConsumer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.snuba.spansConsumer.livenessProbe.periodSeconds }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.spansConsumer.env }}
{{ toYaml .Values.snuba.spansConsumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.spansConsumer.volumeMounts }}
{{ toYaml .Values.snuba.spansConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.spansConsumer.resources | indent 12 }}
{{- if .Values.snuba.spansConsumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.spansConsumer.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.spansConsumer.volumes }}
{{ toYaml .Values.snuba.spansConsumer.volumes | indent 8 }}
{{- end }}
{{- end }}
