apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-relay
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: relay
{{- if not .Values.relay.autoscaling.enabled }}
  replicas: {{ .Values.relay.replicas }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/relay: {{ .Values.config.relay | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-relay.yaml") . | sha256sum }}
        {{- if .Values.relay.annotations }}
{{ toYaml .Values.relay.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: relay
        {{- if .Values.relay.podLabels }}
{{ toYaml .Values.relay.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.relay.affinity }}
{{ toYaml .Values.relay.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.relay.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.relay.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.relay.tolerations }}
      tolerations:
{{ toYaml .Values.relay.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.relay.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.relay.imagePullSecrets | indent 8 }}
      {{- end }}
      initContainers:
        - name: {{ .Chart.Name }}-relay-init
          image: {{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag }}
          args:
            - "credentials"
            - "generate"
          env:
            - name: RELAY_PORT
              value: {{ template "relay.port" }}
          volumeMounts:
            - name: credentials
              mountPath: /work/.relay
            - name: config
              mountPath: /work/.relay/config.yml
              subPath: config.yml
              readOnly: true
      containers:
      - name: {{ .Chart.Name }}-relay
        image: "{{ .Values.images.relay.repository }}:{{ .Values.images.relay.tag }}"
        imagePullPolicy: {{ .Values.images.relay.pullPolicy }}
        # command: ["/bin/bash", "-c"]
        # args: ["mkdir -p /work/.relay; cp /work/config.yml /work/.relay/config.yml;ls /work/.relay;relay credentials generate --stdout > /work/.relay/credentials.json;chmod +x /docker-entrypoint.sh;echo 'Creating credentials';/docker-entrypoint.sh credentials generate  --overwrite;echo 'Done creating credentials.';ls /work/.relay;cat /work/.relay/credentials.json;/docker-entrypoint.sh run"]
        ports:
        - containerPort: {{ template "relay.port" }}
        env:
        - name: RELAY_PORT
          value: "{{ template 'relay.port' }}"
{{- if .Values.relay.env }}
{{ toYaml .Values.relay.env | indent 8 }}
{{- end }}
        volumeMounts:
          - name: credentials
            mountPath: /work/.relay
          - name: config
            mountPath: /work/.relay/config.yml
            subPath: config.yml
            readOnly: true
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/relay/healthcheck/ready/
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/relay/healthcheck/ready/
            port: {{ template "relay.port" }}
            scheme: HTTP
          initialDelaySeconds: {{ .Values.relay.probeInitialDelaySeconds }}
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
{{ toYaml .Values.relay.resources | indent 12 }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-relay
          defaultMode: 0644
      - name: credentials
        emptyDir: {}
      {{- if .Values.relay.priorityClassName }}
      priorityClassName: "{{ .Values.relay.priorityClassName }}"
      {{- end }}
