{{- if .Values.sentry.ingestConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-ingest-consumer-attachments
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}
      release: "{{ .Release.Name }}"
      role: ingest-consumer
{{- if not .Values.sentry.ingestConsumer.autoscaling.enabled }}
  replicas: {{ .Values.sentry.ingestConsumer.replicas }}
{{- end }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
        {{- if .Values.sentry.ingestConsumer.annotations }}
{{ toYaml .Values.sentry.ingestConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: ingest-consumer
        {{- if .Values.sentry.ingestConsumer.podLabels }}
{{ toYaml .Values.sentry.ingestConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.ingestConsumer.affinity }}
{{ toYaml .Values.sentry.ingestConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.ingestConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.ingestConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.ingestConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.ingestConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.ingestConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.ingestConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-ingest-consumer-attachments
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "ingest-attachments"
          - "--consumer-group"
          - "ingest-consumer"
          {{- if .Values.sentry.ingestConsumer.concurrency }}
          - "--concurrency"
          - "{{ .Values.sentry.ingestConsumer.concurrency }}"
          {{- end }}
          {{- if .Values.sentry.ingestConsumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.sentry.ingestConsumer.maxBatchSize }}"
          {{- end }}
        env:
        - name: C_FORCE_ROOT
          value: "true"
{{ include "sentry.env" . | indent 8 }}
{{- if .Values.sentry.ingestConsumer.env }}
{{ toYaml .Values.sentry.ingestConsumer.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
        {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.ingestConsumer.volumeMounts }}
{{ toYaml .Values.sentry.ingestConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.ingestConsumer.resources | indent 12 }}
{{- if .Values.sentry.ingestConsumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.ingestConsumer.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.ingestConsumer.sidecars }}
{{ toYaml .Values.sentry.ingestConsumer.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-ingest-consumer-attachments
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ .Values.filestore.gcs.secretName }}
      {{ end }}
{{- if .Values.sentry.ingestConsumer.volumes }}
{{ toYaml .Values.sentry.ingestConsumer.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.ingestConsumer.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.ingestConsumer.priorityClassName }}"
      {{- end }}
{{- end }}
