{{- if .Values.snuba.replacer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-replacer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-replacer
  replicas: {{ .Values.snuba.replacer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.snuba.config" . | sha256sum }}
        {{- if .Values.snuba.replacer.annotations }}
{{ toYaml .Values.snuba.replacer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-replacer
        {{- if .Values.snuba.replacer.podLabels }}
{{ toYaml .Values.snuba.replacer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.replacer.affinity }}
{{ toYaml .Values.snuba.replacer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.replacer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.replacer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.replacer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.replacer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.replacer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.replacer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "replacer"
          - "--storage"
          - "errors"
          - "--auto-offset-reset"
          - "{{ .Values.snuba.replacer.autoOffsetReset }}"
          {{- if .Values.snuba.replacer.maxBatchTimeMs }}
          - "--max-batch-time-ms"
          - "{{ .Values.snuba.replacer.maxBatchTimeMs }}"
          {{- end }}
          {{- if .Values.snuba.replacer.queuedMaxMessagesKbytes }}
          - "--queued-max-messages-kbytes"
          - "{{ .Values.snuba.replacer.queuedMaxMessagesKbytes }}"
          {{- end }}
          {{- if .Values.snuba.replacer.queuedMinMessages }}
          - "--queued-min-messages"
          - "{{ .Values.snuba.replacer.queuedMinMessages }}"
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.replacer.env }}
{{ toYaml .Values.snuba.replacer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.replacer.volumeMounts }}
{{ toYaml .Values.snuba.replacer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.replacer.resources | indent 12 }}
{{- if .Values.snuba.replacer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.replacer.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.replacer.volumes }}
{{ toYaml .Values.snuba.replacer.volumes | indent 6 }}
{{- end }}
{{- end }}
