{{- if .Values.snuba.subscriptionConsumerMetrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-subscription-consumer-metrics
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "18"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-metrics
  replicas: {{ .Values.snuba.subscriptionConsumerMetrics.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.subscriptionConsumerMetrics.annotations }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-subscription-consumer-metrics
        {{- if .Values.snuba.subscriptionConsumerMetrics.podLabels }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.subscriptionConsumerMetrics.affinity }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerMetrics.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerMetrics.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerMetrics.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        command:
          - "snuba"
          - "subscriptions-scheduler-executor"
          - "--auto-offset-reset={{ .Values.snuba.subscriptionConsumerMetrics.autoOffsetReset }}"
          - "--dataset=metrics"
          - "--entity=metrics_sets"
          - "--entity=metrics_counters"
          {{- if .Values.snuba.subscriptionConsumerMetrics.noStrictOffsetReset }}
          - "--no-strict-offset-reset"
          {{- end }}
          - "--consumer-group=nuba-metrics-subscriptions-consumers"
          - "--followed-consumer-group=snuba-metrics-consumers"
          - "--schedule-ttl=60"
          - "--stale-threshold-seconds=900"
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.subscriptionConsumerMetrics.env }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
{{- if .Values.snuba.subscriptionConsumerMetrics.volumeMounts }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.resources | indent 12 }}
{{- if .Values.snuba.subscriptionConsumerMetrics.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.containerSecurityContext | indent 12 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-snuba
{{- if .Values.snuba.subscriptionConsumerMetrics.volumes }}
{{ toYaml .Values.snuba.subscriptionConsumerMetrics.volumes | indent 6 }}
{{- end }}
{{- end }}
