{{- if .Values.sentry.postProcessForwardErrors.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-post-process-forward-errors
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-post-process-forward-errors
  replicas: {{ .Values.sentry.postProcessForwardErrors.replicas }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-sentry.yaml") . | sha256sum }}
        {{- if .Values.sentry.postProcessForwardErrors.annotations }}
{{ toYaml .Values.sentry.postProcessForwardErrors.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: sentry-post-process-forward-errors
        {{- if .Values.sentry.postProcessForwardErrors.podLabels }}
{{ toYaml .Values.sentry.postProcessForwardErrors.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.postProcessForwardErrors.affinity }}
{{ toYaml .Values.sentry.postProcessForwardErrors.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.postProcessForwardErrors.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.postProcessForwardErrors.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.postProcessForwardErrors.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.postProcessForwardErrors.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.postProcessForwardErrors.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.postProcessForwardErrors.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-post-process-forward-errors
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer" 
          - "post-process-forwarder-errors"
          - "--consumer-group"
          - "post-process-forwarder"
          - "--synchronize-commit-log-topic=snuba-commit-log"
          - "--synchronize-commit-group=snuba-consumers"
        env:
{{ include "sentry.env" . | indent 8 }}
{{- if .Values.sentry.postProcessForwardErrors.env }}
{{ toYaml .Values.sentry.postProcessForwardErrors.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
        {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.postProcessForwardErrors.volumeMounts }}
{{ toYaml .Values.sentry.postProcessForwardErrors.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.postProcessForwardErrors.resources | indent 12 }}
{{- if .Values.sentry.postProcessForwardErrors.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.postProcessForwardErrors.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.postProcessForwardErrors.sidecars }}
{{ toYaml .Values.sentry.postProcessForwardErrors.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-post-process-forwarder-errors
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ .Values.filestore.gcs.secretName }}
      {{ end }}
{{- if .Values.sentry.postProcessForwardErrors.volumes }}
{{ toYaml .Values.sentry.postProcessForwardErrors.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.postProcessForwardErrors.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.postProcessForwardErrors.priorityClassName }}"
      {{- end }}
{{- end }}
