{{- if .Values.sentry.genericMetricsConsumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-generic-metrics-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "10"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "sentry.fullname" . }}
      release: "{{ .Release.Name }}"
      role: generic-metrics-consumer
  replicas: {{ .Values.sentry.genericMetricsConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/configYml: {{ .Values.config.configYml | toYaml | toString | sha256sum }}
        checksum/sentryConfPy: {{ .Values.config.sentryConfPy | sha256sum }}
        checksum/config.yaml: {{ include "sentry.config" . | sha256sum }}
        {{- if .Values.sentry.genericMetricsConsumer.annotations }}
{{ toYaml .Values.sentry.genericMetricsConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: generic-metrics-consumer
        {{- if .Values.sentry.genericMetricsConsumer.podLabels }}
{{ toYaml .Values.sentry.genericMetricsConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.sentry.genericMetricsConsumer.affinity }}
{{ toYaml .Values.sentry.genericMetricsConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.genericMetricsConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.sentry.genericMetricsConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.genericMetricsConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.sentry.genericMetricsConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.sentry.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.sentry.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.sentry.genericMetricsConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.sentry.genericMetricsConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-generic-metrics-consumer
        image: "{{ template "sentry.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.sentry.pullPolicy }}
        command: ["sentry"]
        args:
          - "run"
          - "consumer"
          - "ingest-generic-metrics"
          - "--consumer-group"
          - "generic-metrics-consumer"
          {{- if .Values.sentry.genericMetricsConsumer.livenessProbe.enabled }}
          - "--healthcheck-file-path"
          - "/tmp/health.txt"
          {{- end }}
          - "--"
          {{- if .Values.sentry.genericMetricsConsumer.maxBatchSize }}
          - "--max-batch-size"
          - "{{ .Values.sentry.genericMetricsConsumer.maxBatchSize }}"
          {{- end }}
          {{- if .Values.sentry.genericMetricsConsumer.concurrency }}
          - "--processes"
          - "{{ .Values.sentry.genericMetricsConsumer.concurrency }}"
          {{- end }}
        {{- if .Values.sentry.genericMetricsConsumer.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - rm
              - /tmp/health.txt
          initialDelaySeconds: {{ .Values.sentry.genericMetricsConsumer.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.sentry.genericMetricsConsumer.livenessProbe.periodSeconds }}
        {{- end }}
        env:
        - name: C_FORCE_ROOT
          value: "true"
{{ include "sentry.env" . | indent 8 }}
{{- if .Values.sentry.genericMetricsConsumer.env }}
{{ toYaml .Values.sentry.genericMetricsConsumer.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/sentry
          name: config
          readOnly: true
        - mountPath: {{ .Values.filestore.filesystem.path }}
          name: sentry-data
        {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
        - name: sentry-google-cloud-key
          mountPath: /var/run/secrets/google
        {{ end }}
{{- if .Values.sentry.genericMetricsConsumer.volumeMounts }}
{{ toYaml .Values.sentry.genericMetricsConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.sentry.genericMetricsConsumer.resources | indent 12 }}
{{- if .Values.sentry.genericMetricsConsumer.containerSecurityContext }}
        securityContext:
{{ toYaml .Values.sentry.genericMetricsConsumer.containerSecurityContext | indent 12 }}
{{- end }}
{{- if .Values.sentry.genericMetricsConsumer.sidecars }}
{{ toYaml .Values.sentry.genericMetricsConsumer.sidecars | indent 6 }}
{{- end }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-generic-metrics-consumer
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "sentry.fullname" . }}-sentry
      - name: sentry-data
      {{- if and (eq .Values.filestore.backend "filesystem") .Values.filestore.filesystem.persistence.enabled (.Values.filestore.filesystem.persistence.persistentWorkers) }}
      {{- if .Values.filestore.filesystem.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.filestore.filesystem.persistence.existingClaim }}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "sentry.fullname" . }}-data
      {{- end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
      {{- if and (eq .Values.filestore.backend "gcs") .Values.filestore.gcs.secretName }}
      - name: sentry-google-cloud-key
        secret:
          secretName: {{ .Values.filestore.gcs.secretName }}
      {{ end }}
{{- if .Values.sentry.genericMetricsConsumer.volumes }}
{{ toYaml .Values.sentry.genericMetricsConsumer.volumes | indent 6 }}
{{- end }}
      {{- if .Values.sentry.genericMetricsConsumer.priorityClassName }}
      priorityClassName: "{{ .Values.sentry.genericMetricsConsumer.priorityClassName }}"
      {{- end }}
{{- end }}
