apiVersion: v1
appVersion: "23.3.19.32"
description: ClickHouse is an open source column-oriented database management
  system capable of real time generation of analytical data reports using SQL
  queries
home: https://clickhouse.yandex/
icon: https://clickhouse.yandex/images/logo.png
keywords:
  - clickhouse
  - olap
  - database
name: clickhouse
sources:
  - https://github.com/sentry-kubernetes/charts
version: 3.13.0
maintainers:
  - name: sentry-kubernetes
