name: Lint and Test Charts

on: pull_request

jobs:
  lint-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.1.0
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch=develop --chart-dirs=. )
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Lint Sentry Helm Chart
        uses: WyriHaximus/github-action-helm3@v2
        if: steps.list-changed.outputs.changed == 'true'
        with:
          exec: for chart in $(ls -d ./*/); do helm lint $chart; done
      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          ct lint \
            --target-branch=develop \
            --chart-dirs=. \
            --chart-repos=bitnami=https://charts.bitnami.com/bitnami,bitnami-old=https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami,sentry-kubernetes=https://sentry-kubernetes.github.io/charts
     # It would be nice to turn on this testing, but it is hard to get right and
     # rather complex (as well as expensive in terms of runner compute time).
     # Additionally, this is out of scope of fixing the issue brought up in #456
     # - name: Create kind cluster
     #   uses: helm/kind-action@v1.2.0
     #   if: steps.list-changed.outputs.changed == 'true'
     # - name: Run chart-testing (install)
     #   run: ct install --target-branch=develop --chart-dirs=.
