name: Build and push Chart

on:
  push:
    tags:
      - '*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          path: 'main'

      - uses: actions/checkout@v4
        with:
          path: 'gh-pages'

      - run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout gh-pages

      - name: Build clickhouse chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm package -u main/charts/clickhouse --destination gh-pages/charts

      - name: Build sentry chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm package -u main/charts/sentry --destination gh-pages/charts

      - name: Build sentry-kubernetes chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm package -u main/charts/sentry-kubernetes --destination gh-pages/charts

      - name: Build sentry-kubernetes chart
        uses: WyriHaximus/github-action-helm3@v4
        with:
          exec: helm repo index --url https://sentry-kubernetes.github.io/charts ./gh-pages/charts

      - name: Commit files
        run: |
          cd gh-pages
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@77c5b412c50b723d2a4fbc6d71fb5723bcd439aa
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gh-pages/charts
        with:
          keepFiles: true
