name: Build and push Chart

on:
  push:
    tags:
      - '*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          path: 'main'

      - uses: actions/checkout@v4
        with:
          path: 'gh-pages'

      - run: |
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git checkout gh-pages

      - name: Build clickhouse chart
        uses: yeouchien/helm3-action@d143356cad04091228a880bb987108182e31234c
        with:
          command: package -u main/clickhouse --destination gh-pages/charts

      - name: Build sentry chart
        uses: yeouchien/helm3-action@d143356cad04091228a880bb987108182e31234c
        with:
          command: package -u main/sentry --destination gh-pages/charts

      - name: Build sentry-kubernetes chart
        uses: yeouchien/helm3-action@d143356cad04091228a880bb987108182e31234c
        with:
          command: package -u main/sentry-kubernetes --destination gh-pages/charts

      - name: Create index file
        uses: yeouchien/helm3-action@d143356cad04091228a880bb987108182e31234c
        with:
          command: repo index --url https://sentry-kubernetes.github.io/charts ./gh-pages/charts

      - name: Commit files
        run: |
          cd gh-pages
          git add .
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@19caa5c351f47734055690f7d01aaaef2f9114d5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./gh-pages/charts
        with:
          keepFiles: true
