{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-nginx
data:
  server-block.conf: |
    {{ if .Values.relay.enabled }}
    upstream relay {
      server {{ template "sentry.fullname" . }}-relay:{{ template "relay.port" }};
    }
    {{ end -}}

    upstream sentry {
      server {{ template "sentry.fullname" . }}-web:{{ template "sentry.port" }};
    }

    server {
      listen {{ template "nginx.port" }};
      {{- if .Values.ipv6 }}
      listen [::]:{{ template "nginx.port" }};
      {{- end }}

      proxy_redirect off;
      proxy_buffer_size          128k;
      proxy_buffers              4 256k;
      proxy_busy_buffers_size    256k;
      proxy_set_header Host $host;

      {{ if .Values.relay.enabled }}
      location /api/store/ {
        proxy_pass http://relay;
      }

      location ~ ^/api/[1-9]\d*/ {
        proxy_pass http://relay;
      }

      location ^~ /api/0/relays/ {
        proxy_pass http://relay;
      }
      {{ end -}}

      {{ if or .Values.nginx.metrics.enabled .Values.nginx.metrics.serviceMonitor.enabled -}}
      location = /status/ {
        stub_status on;
        access_log off;
      }

      {{ end -}}

      location / {
        proxy_pass http://sentry;
      }

      location /_static/ {
        proxy_pass http://sentry;
        proxy_hide_header Content-Disposition;
      }

      {{- if .Values.nginx.extraLocationSnippet }}
      {{ .Values.nginx.extraLocationSnippet | nindent 6 }}
      {{- end }}

    }
{{- end }}
