apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.prefix" . }}snuba-replacer
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: snuba-replacer
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.replacer.annotations }}
{{ toYaml .Values.snuba.replacer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: sentry
        release: "{{ .Release.Name }}"
        role: snuba-replacer
        {{- if .Values.snuba.replacer.podLabels }}
{{ toYaml .Values.snuba.replacer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.replacer.affinity }}
{{ toYaml .Values.snuba.replacer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.replacer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.replacer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.replacer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.replacer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ .Values.images.snuba.repository }}:{{ .Values.images.snuba.tag }}"
        imagePullPolicy: {{ .Values.images.snuba.pullPolicy }}
        command: ["snuba", "replacer", "--auto-offset-reset=latest", "--max-batch-size",  "3"]
        ports:
        - containerPort: {{ template "snuba.port" }}
        envFrom:
        - configMapRef:
            name: {{ template "sentry.prefix" . }}snuba
{{- if .Values.snuba.replacer.env }}
        env:
{{ toYaml .Values.snuba.replacer.env | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.replacer.resources | indent 12 }}
